import type { RoomTemplateRow, ScopeDefaultRow, UnitRateRow } from '../../../types/estimator/ratesFlags'
import type { CategoryConfig } from './categoryTypes.ts'
import { asDisplayName, asText, normalizeId, toYNString } from './shared.ts'

export const DOORS_CATEGORY_CONFIGS: CategoryConfig[] = [
  {
    key: 'unit_rates_doors',
    tab: 'rates',
    group: 'unit_rates',
    label: 'Unit Rates - Doors',
    tableTitles: ['CAT_DoorsInterior', 'CAT_DoorTypes', 'Door Types'],
    additionalTableTitles: [['CAT_DoorsExterior']],
    mergeAdditionalTableTitles: true,
    description: 'Per-unit assumptions for interior/exterior door scope.',
    columns: [
      { key: 'id', label: 'Rate ID' },
      { key: 'display_name', label: 'Name' },
      { key: 'unit_rate_type', label: 'Type' },
      { key: 'unit', label: 'Unit' },
      { key: 'labor_rate', label: 'Labor', align: 'right' },
      { key: 'material_rate', label: 'Material', align: 'right' },
      { key: 'amount', label: 'Amount', align: 'right' },
      { key: 'active', label: 'Status', align: 'center' },
    ],
    fields: [
      { key: 'unit_rate_group', label: 'Unit Group', type: 'select', readOnly: true, options: ['doors'], headers: ['UnitRateGroup'], writeDefault: 'doors' },
      { key: 'id', label: 'Rate ID', type: 'text', required: true, headers: ['DoorTypeID', 'DoorID', 'ID'] },
      { key: 'display_name', label: 'Display Name', type: 'text', required: true, headers: ['DisplayName', 'Name', 'Label'] },
      { key: 'unit_rate_type', label: 'Type', type: 'text', headers: ['Type', 'Category', 'Subtype'] },
      { key: 'unit', label: 'Unit', type: 'text', headers: ['Unit', 'UOM'] },
      { key: 'default_qty', label: 'Default Qty', type: 'number', headers: ['DefaultQty', 'QtyDefault', 'Qty'] },
      { key: 'labor_rate', label: 'Labor', type: 'number', headers: ['LaborRate', 'LaborHours', 'LaborHrs_Each', 'Man_Hours_each', 'Hours_Each'] },
      { key: 'material_rate', label: 'Material', type: 'number', headers: ['MaterialRate', 'Materials$_Each', 'MaterialsEach', 'ExtraSupplies'] },
      { key: 'amount', label: 'Amount', type: 'number', headers: ['Amount', 'Value', 'Rate', 'Cost', 'Price_each'] },
      { key: 'notes', label: 'Notes', type: 'text', headers: ['Notes', 'Note'] },
    ],
    toRow(values, active) {
      return {
        id: normalizeId(values.id),
        unit_rate_group: 'doors',
        display_name: asDisplayName(values),
        unit_rate_type: asText(values.unit_rate_type),
        unit: asText(values.unit),
        default_qty: asText(values.default_qty),
        labor_rate: asText(values.labor_rate),
        material_rate: asText(values.material_rate),
        amount: asText(values.amount),
        notes: asText(values.notes),
        active,
      } satisfies UnitRateRow
    },
  },
  {
    key: 'room_templates',
    tab: 'room_defaults',
    group: 'room_templates',
    label: 'Room Templates',
    tableTitles: ['CAT_RoomTemplates', 'Room Templates'],
    additionalTableTitles: [['CAT_RoomTypes']],
    description: 'Template presets for creating full room scope defaults.',
    columns: [
      { key: 'id', label: 'Template ID' },
      { key: 'display_name', label: 'Name' },
      { key: 'room_type_id', label: 'Room Type' },
      { key: 'default_wall_mode', label: 'Wall Mode' },
      { key: 'include_walls', label: 'Walls' },
      { key: 'include_ceilings', label: 'Ceilings' },
      { key: 'active', label: 'Status', align: 'center' },
    ],
    fields: [
      { key: 'id', label: 'Template ID', type: 'text', required: true, headers: ['RoomTemplateID', 'TemplateID', 'RoomTypeID', 'ID'] },
      { key: 'display_name', label: 'Display Name', type: 'text', required: true, headers: ['DisplayName', 'TemplateName', 'Name', 'Label'] },
      { key: 'room_type_id', label: 'Room Type ID', type: 'text', headers: ['RoomTypeID', 'TypeID'] },
      { key: 'default_wall_rate_id', label: 'Default Wall Rate ID', type: 'text', headers: ['DefaultWallRateID', 'WallRateID'] },
      { key: 'default_ceil_rate_id', label: 'Default Ceiling Rate ID', type: 'text', headers: ['DefaultCeilRateID', 'CeilRateID'] },
      { key: 'default_complexity_id', label: 'Default Complexity ID', type: 'text', headers: ['DefaultComplexityID', 'ComplexityTypeID', 'WallComplexityTypeID'] },
      { key: 'default_wall_mode', label: 'Default Wall Mode', type: 'select', options: ['RECT', 'SEG'], headers: ['DefaultWallMode', 'WallMode'] },
      { key: 'include_walls', label: 'Include Walls', type: 'select', options: ['Y', 'N'], headers: ['IncludeWalls', 'WallsInclude'], writeDefault: 'Y' },
      { key: 'include_ceilings', label: 'Include Ceilings', type: 'select', options: ['Y', 'N'], headers: ['IncludeCeilings', 'CeilingInclude'], writeDefault: 'N' },
      { key: 'include_trim', label: 'Include Trim', type: 'select', options: ['Y', 'N'], headers: ['IncludeTrim', 'TrimInclude'], writeDefault: 'N' },
      { key: 'include_doors', label: 'Include Doors', type: 'select', options: ['Y', 'N'], headers: ['IncludeDoors', 'DoorsInclude'], writeDefault: 'N' },
      { key: 'include_drywall', label: 'Include Drywall', type: 'select', options: ['Y', 'N'], headers: ['IncludeDrywall', 'DrywallInclude'], writeDefault: 'N' },
      { key: 'notes', label: 'Notes', type: 'text', headers: ['Notes', 'Note'] },
    ],
    toRow(values, active) {
      return {
        id: normalizeId(values.id),
        display_name: asDisplayName(values),
        room_type_id: asText(values.room_type_id),
        default_wall_rate_id: asText(values.default_wall_rate_id),
        default_ceil_rate_id: asText(values.default_ceil_rate_id),
        default_complexity_id: asText(values.default_complexity_id),
        default_wall_mode: asText(values.default_wall_mode),
        include_walls: toYNString(asText(values.include_walls)),
        include_ceilings: toYNString(asText(values.include_ceilings)),
        include_trim: toYNString(asText(values.include_trim)),
        include_doors: toYNString(asText(values.include_doors)),
        include_drywall: toYNString(asText(values.include_drywall)),
        notes: asText(values.notes),
        active,
      } satisfies RoomTemplateRow
    },
  },
  {
    key: 'scope_defaults',
    tab: 'room_defaults',
    group: 'scope_defaults',
    label: 'Scope Defaults',
    tableTitles: ['CAT_ScopeDefaults', 'Scope Defaults'],
    additionalTableTitles: [['CAT_RoomTemplates'], ['CAT_RoomTypes']],
    description: 'Default included scopes and wall behavior presets.',
    columns: [
      { key: 'id', label: 'Default ID' },
      { key: 'display_name', label: 'Name' },
      { key: 'default_wall_mode', label: 'Wall Mode' },
      { key: 'typical_height_ft', label: 'Typical Height (ft)', align: 'right' },
      { key: 'include_walls', label: 'Walls' },
      { key: 'include_ceilings', label: 'Ceilings' },
      { key: 'active', label: 'Status', align: 'center' },
    ],
    fields: [
      { key: 'id', label: 'Default ID', type: 'text', required: true, headers: ['ScopeDefaultID', 'RoomTemplateID', 'TemplateID', 'RoomTypeID', 'ID'] },
      { key: 'display_name', label: 'Display Name', type: 'text', required: true, headers: ['DisplayName', 'TemplateName', 'Name', 'Label'] },
      { key: 'default_wall_mode', label: 'Default Wall Mode', type: 'select', options: ['RECT', 'SEG'], headers: ['DefaultWallMode', 'WallMode'] },
      { key: 'top_cut_in_factor', label: 'Top Cut-In Factor', type: 'number', headers: ['TopCutInFactor', 'Top Cut In Factor'] },
      { key: 'bot_cut_in_factor', label: 'Bottom Cut-In Factor', type: 'number', headers: ['BotCutInFactor', 'Bottom Cut In Factor'] },
      { key: 'typical_height_ft', label: 'Typical Height (ft)', type: 'number', headers: ['TypicalHeight_ft', 'DefaultHeight_ft', 'Height_ft'] },
      { key: 'include_walls', label: 'Include Walls', type: 'select', options: ['Y', 'N'], headers: ['IncludeWalls', 'WallsInclude'], writeDefault: 'Y' },
      { key: 'include_ceilings', label: 'Include Ceilings', type: 'select', options: ['Y', 'N'], headers: ['IncludeCeilings', 'CeilingInclude'], writeDefault: 'N' },
      { key: 'include_trim', label: 'Include Trim', type: 'select', options: ['Y', 'N'], headers: ['IncludeTrim', 'TrimInclude'], writeDefault: 'N' },
      { key: 'include_doors', label: 'Include Doors', type: 'select', options: ['Y', 'N'], headers: ['IncludeDoors', 'DoorsInclude'], writeDefault: 'N' },
      { key: 'include_drywall', label: 'Include Drywall', type: 'select', options: ['Y', 'N'], headers: ['IncludeDrywall', 'DrywallInclude'], writeDefault: 'N' },
      { key: 'notes', label: 'Notes', type: 'text', headers: ['Notes', 'Note'] },
    ],
    toRow(values, active) {
      return {
        id: normalizeId(values.id),
        display_name: asDisplayName(values),
        default_wall_mode: asText(values.default_wall_mode),
        top_cut_in_factor: asText(values.top_cut_in_factor),
        bot_cut_in_factor: asText(values.bot_cut_in_factor),
        typical_height_ft: asText(values.typical_height_ft),
        include_walls: toYNString(asText(values.include_walls)),
        include_ceilings: toYNString(asText(values.include_ceilings)),
        include_trim: toYNString(asText(values.include_trim)),
        include_doors: toYNString(asText(values.include_doors)),
        include_drywall: toYNString(asText(values.include_drywall)),
        notes: asText(values.notes),
        active,
      } satisfies ScopeDefaultRow
    },
  },
]
