import type { CSSProperties } from 'react'

export const S: Record<string, CSSProperties> = {
  tokens: {
    '--v2-bg': '#0a0a0a',
    '--v2-bg-2': '#131313',
    '--v2-bg-3': '#1a1a1a',
    '--v2-line': '#262626',
    '--v2-line-2': '#333333',
    '--v2-ink': '#f5f5f5',
    '--v2-ink-2': '#c5c5c5',
    '--v2-ink-3': '#7a7a7a',
    '--v2-green': '#84cc93',
    '--v2-green-2': '#a7d9b4',
    '--v2-green-dim': '#2f5a3a',
    '--v2-green-wash': 'rgba(132, 204, 147, 0.08)',
    '--v2-green-deep': '#0f2416',
    '--v2-red': '#f87171',
    '--v2-amber': '#fbbf24',
    '--v2-mono': "'JetBrains Mono', ui-monospace, monospace",
    color: 'var(--v2-ink)',
    fontFamily: "'Inter', system-ui, sans-serif",
    minWidth: 0,
  } as CSSProperties,
  main: {
    display: 'block',
    minWidth: 0,
    minHeight: '100vh',
    background: 'var(--v2-bg)',
    color: 'var(--v2-ink)',
    overflowX: 'hidden',
  },
  content: {
    width: '100%',
    padding: '24px 28px 48px',
    maxWidth: 'none',
    margin: 0,
    scrollBehavior: 'smooth',
  },
  desktopWrap: {
    display: 'block',
  },
  topRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 24,
    paddingBottom: 20,
    borderBottom: '1px solid var(--v2-line)',
    marginBottom: 32,
  },
  brandWrap: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
  },
  brandMark: {
    width: 40,
    height: 40,
    borderRadius: 10,
    background: 'linear-gradient(180deg, #092b16 0%, #04180d 100%)',
    border: '1px solid var(--v2-green-dim)',
    color: 'var(--v2-green-2)',
    display: 'grid',
    placeItems: 'center',
    fontFamily: 'var(--v2-mono)',
    fontSize: 14,
    fontWeight: 700,
    flexShrink: 0,
  },
  brandName: {
    fontWeight: 800,
    fontSize: 18,
    color: 'var(--v2-ink)',
    letterSpacing: '-0.02em',
  },
  brandSub: {
    fontFamily: 'var(--v2-mono)',
    fontSize: 10,
    color: 'var(--v2-ink-3)',
    letterSpacing: '0.14em',
    textTransform: 'uppercase',
    marginTop: 2,
  },
  crumbs: {
    fontFamily: 'var(--v2-mono)',
    fontSize: 11,
    color: 'var(--v2-ink-3)',
    letterSpacing: '0.14em',
    textTransform: 'uppercase',
    marginTop: 8,
  },
  topControls: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    flexWrap: 'wrap',
    justifyContent: 'flex-end',
  },
  settingsMenu: {
    position: 'relative',
  },
  settingsSummary: {
    listStyle: 'none',
    display: 'inline-flex',
    alignItems: 'center',
    gap: 10,
    padding: '11px 14px',
    borderRadius: 12,
    border: '1px solid var(--v2-line)',
    background: 'var(--v2-bg-2)',
    color: 'var(--v2-ink)',
    fontSize: 13,
    fontWeight: 700,
    cursor: 'pointer',
    userSelect: 'none',
    whiteSpace: 'nowrap',
  },
  settingsPanel: {
    position: 'absolute',
    right: 0,
    top: 'calc(100% + 10px)',
    width: 240,
    padding: 10,
    borderRadius: 14,
    border: '1px solid var(--v2-line)',
    background: 'var(--v2-bg-2)',
    boxShadow: '0 16px 42px rgba(0,0,0,0.38)',
    display: 'grid',
    gap: 6,
    zIndex: 20,
  },
  settingsLink: {
    display: 'block',
    padding: '10px 12px',
    borderRadius: 10,
    border: '1px solid transparent',
    background: 'transparent',
    color: 'var(--v2-ink-2)',
    textDecoration: 'none',
    fontSize: 13,
    fontWeight: 600,
  },
  settingsDisabled: {
    display: 'block',
    padding: '10px 12px',
    borderRadius: 10,
    color: 'var(--v2-ink-3)',
    fontSize: 13,
    fontWeight: 600,
    cursor: 'default',
  },
  searchWrap: {
    position: 'relative',
    display: 'flex',
    alignItems: 'center',
    gap: 10,
  },
  search: {
    width: 380,
    minWidth: 0,
    padding: '13px 14px',
    borderRadius: 12,
    border: '1px solid var(--v2-line)',
    background: 'var(--v2-bg-2)',
    color: 'var(--v2-ink-2)',
    fontSize: 14,
  },
  searchResults: {
    position: 'absolute',
    top: 'calc(100% + 10px)',
    left: 0,
    width: 380,
    maxHeight: 320,
    overflowY: 'auto',
    borderRadius: 14,
    border: '1px solid var(--v2-line)',
    background: 'var(--v2-bg-2)',
    boxShadow: '0 16px 42px rgba(0,0,0,0.38)',
    zIndex: 20,
    padding: 8,
    display: 'grid',
    gap: 6,
  },
  searchResultLink: {
    display: 'block',
    padding: '10px 12px',
    borderRadius: 10,
    border: '1px solid transparent',
    color: 'var(--v2-ink)',
    textDecoration: 'none',
    background: 'rgba(255,255,255,0.02)',
  },
  searchStatusPanel: {
    padding: 14,
    borderRadius: 10,
    border: '1px solid var(--v2-line)',
    background: 'rgba(255,255,255,0.02)',
    display: 'grid',
    gap: 10,
  },
  searchStatusTitle: {
    fontSize: 14,
    fontWeight: 700,
    color: 'var(--v2-ink)',
  },
  searchStatusText: {
    fontSize: 13,
    lineHeight: 1.5,
    color: 'var(--v2-ink-3)',
  },
  searchRetryButton: {
    justifySelf: 'start',
    padding: '9px 12px',
    borderRadius: 10,
    border: '1px solid rgba(134,239,172,0.24)',
    background: 'rgba(74,222,128,0.08)',
    color: '#b7f3c9',
    fontSize: 12,
    fontWeight: 700,
    cursor: 'pointer',
  },
  eyebrow: {
    fontFamily: 'var(--v2-mono)',
    fontSize: 11,
    color: 'var(--v2-ink-3)',
    letterSpacing: '0.16em',
    textTransform: 'uppercase',
    marginBottom: 10,
  },
  heroRow: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 24,
    marginBottom: 28,
  },
  h1: {
    margin: 0,
    fontSize: 28,
    lineHeight: 1.12,
    letterSpacing: '-0.03em',
    fontWeight: 700,
    color: 'var(--v2-ink)',
  },
  subhead: {
    marginTop: 8,
    fontSize: 15,
    lineHeight: 1.7,
    color: 'var(--v2-ink-2)',
    maxWidth: 760,
  },
  card: {
    background: 'var(--v2-bg-2)',
    border: '1px solid var(--v2-line)',
    borderRadius: 16,
    padding: 20,
  },
  cardLabel: {
    fontFamily: 'var(--v2-mono)',
    fontSize: 10,
    color: 'var(--v2-ink-3)',
    letterSpacing: '0.16em',
    textTransform: 'uppercase',
    marginBottom: 12,
  },
  statValue: {
    fontSize: 24,
    fontWeight: 700,
    letterSpacing: '-0.03em',
    color: 'var(--v2-ink)',
    marginBottom: 8,
  },
  statSub: {
    fontSize: 13,
    color: 'var(--v2-ink-3)',
  },
  estimateTitle: {
    fontSize: 15,
    fontWeight: 700,
    color: 'var(--v2-ink)',
    marginBottom: 4,
  },
  estimateMeta: {
    fontFamily: 'var(--v2-mono)',
    fontSize: 12,
    color: 'var(--v2-ink-3)',
    lineHeight: 1.6,
  },
  emptyState: {
    padding: '14px 0',
    color: 'var(--v2-ink-3)',
    fontSize: 14,
  },
  mobileScreen: {
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column',
    padding: '18px 16px 100px',
    background: 'var(--v2-bg)',
  },
  mobilePanel: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    gap: 18,
    padding: '14px 14px 22px',
    borderRadius: 30,
    border: '1px solid var(--v2-line)',
    background: 'linear-gradient(180deg, #0b0b0b 0%, #111111 100%)',
    boxShadow: 'inset 0 0 0 1px rgba(255,255,255,0.04)',
  },
  mobileBrandRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    padding: '2px 4px 16px',
    borderBottom: '1px solid var(--v2-line)',
  },
  mobileBrandWrap: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
  },
  mobileBrandMark: {
    width: 28,
    height: 28,
    borderRadius: 8,
    background: 'linear-gradient(180deg, #f3f4f6 0%, #d4d4d8 100%)',
    color: '#0b0b0b',
    display: 'grid',
    placeItems: 'center',
    fontSize: 13,
    fontWeight: 800,
  },
  mobileAvatar: {
    width: 34,
    height: 34,
    borderRadius: 999,
    background: 'rgba(74,222,128,0.14)',
    color: 'var(--v2-green-2)',
    display: 'grid',
    placeItems: 'center',
    fontSize: 13,
    fontWeight: 700,
    fontFamily: 'var(--v2-mono)',
  },
  mobileDate: {
    fontSize: 14,
    color: '#d8d8d8',
    fontWeight: 600,
  },
  mobileTitle: {
    margin: '4px 0 0',
    fontSize: 19,
    lineHeight: 1.15,
    letterSpacing: '-0.03em',
    fontWeight: 700,
    color: 'var(--v2-ink)',
  },
  mobileStats: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    gap: 12,
  },
  mobileStatCard: {
    background: 'var(--v2-bg-2)',
    border: '1px solid var(--v2-line)',
    borderRadius: 14,
    padding: 14,
  },
  mobileSectionLabel: {
    fontFamily: 'var(--v2-mono)',
    fontSize: 10,
    color: 'var(--v2-ink-3)',
    letterSpacing: '0.16em',
    textTransform: 'uppercase',
    marginBottom: 8,
  },
}
