import type { CSSProperties } from 'react'

export const S: Record<string, CSSProperties> = {
  tokens: {
    '--v2-bg': '#0a0a0a',
    '--v2-bg-2': '#131313',
    '--v2-bg-3': '#1a1a1a',
    '--v2-line': '#262626',
    '--v2-line-2': '#333333',
    '--v2-ink': '#f5f5f5',
    '--v2-ink-2': '#c5c5c5',
    '--v2-ink-3': '#7a7a7a',
    '--v2-green': '#84cc93',
    '--v2-green-2': '#a7d9b4',
    '--v2-green-dim': '#2f5a3a',
    '--v2-green-wash': 'rgba(132, 204, 147, 0.08)',
    '--v2-green-deep': '#0f2416',
    '--v2-red': '#f87171',
    '--v2-amber': '#fbbf24',
    '--v2-mono': "'JetBrains Mono', ui-monospace, monospace",
    color: 'var(--v2-ink)',
    fontFamily: "'Inter', system-ui, sans-serif",
    minWidth: 0,
  } as CSSProperties,
  jobHubGrid: {
    display: 'grid',
    gridTemplateColumns: 'minmax(320px, 420px) minmax(0, 1fr)',
    gap: 22,
  },
  jobHubDetailGrid: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1.15fr) minmax(320px, 0.85fr)',
    gap: 22,
  },
  topControls: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    flexWrap: 'wrap',
    justifyContent: 'flex-end',
  },
  headerCard: {
    background: 'var(--v2-bg-2)',
    border: '1px solid var(--v2-line)',
    borderRadius: 16,
    padding: 20,
    display: 'grid',
    gap: 18,
    marginBottom: 24,
  },
  headerRow: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 18,
    flexWrap: 'wrap',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: 700,
    letterSpacing: '-0.02em',
  },
  settingsMenu: {
    position: 'relative',
  },
  settingsSummary: {
    listStyle: 'none',
    display: 'inline-flex',
    alignItems: 'center',
    gap: 10,
    padding: '11px 14px',
    borderRadius: 12,
    border: '1px solid var(--v2-line)',
    background: 'var(--v2-bg-2)',
    color: 'var(--v2-ink)',
    fontSize: 13,
    fontWeight: 700,
    cursor: 'pointer',
    userSelect: 'none',
    whiteSpace: 'nowrap',
  },
  settingsPanel: {
    position: 'absolute',
    right: 0,
    top: 'calc(100% + 10px)',
    width: 240,
    padding: 10,
    borderRadius: 14,
    border: '1px solid var(--v2-line)',
    background: 'var(--v2-bg-2)',
    boxShadow: '0 16px 42px rgba(0,0,0,0.38)',
    display: 'grid',
    gap: 6,
    zIndex: 20,
  },
  settingsLink: {
    display: 'block',
    padding: '10px 12px',
    borderRadius: 10,
    border: '1px solid transparent',
    background: 'transparent',
    color: 'var(--v2-ink-2)',
    textDecoration: 'none',
    fontSize: 13,
    fontWeight: 600,
  },
  settingsDisabled: {
    display: 'block',
    padding: '10px 12px',
    borderRadius: 10,
    color: 'var(--v2-ink-3)',
    fontSize: 13,
    fontWeight: 600,
    cursor: 'default',
  },
  searchWrap: {
    position: 'relative',
    display: 'flex',
    alignItems: 'center',
    gap: 10,
  },
  search: {
    width: 380,
    minWidth: 0,
    padding: '13px 14px',
    borderRadius: 12,
    border: '1px solid var(--v2-line)',
    background: 'var(--v2-bg-2)',
    color: 'var(--v2-ink-2)',
    fontSize: 14,
  },
  searchResults: {
    position: 'absolute',
    top: 'calc(100% + 10px)',
    left: 0,
    width: 380,
    maxHeight: 320,
    overflowY: 'auto',
    borderRadius: 14,
    border: '1px solid var(--v2-line)',
    background: 'var(--v2-bg-2)',
    boxShadow: '0 16px 42px rgba(0,0,0,0.38)',
    zIndex: 20,
    padding: 8,
    display: 'grid',
    gap: 6,
  },
  searchResultLink: {
    display: 'block',
    padding: '10px 12px',
    borderRadius: 10,
    border: '1px solid transparent',
    color: 'var(--v2-ink)',
    textDecoration: 'none',
    background: 'rgba(255,255,255,0.02)',
  },
  searchStatusPanel: {
    padding: 14,
    borderRadius: 10,
    border: '1px solid var(--v2-line)',
    background: 'rgba(255,255,255,0.02)',
    display: 'grid',
    gap: 10,
  },
  searchStatusTitle: {
    fontSize: 14,
    fontWeight: 700,
    color: 'var(--v2-ink)',
  },
  searchStatusText: {
    fontSize: 13,
    lineHeight: 1.5,
    color: 'var(--v2-ink-3)',
  },
  searchRetryButton: {
    justifySelf: 'start',
    padding: '9px 12px',
    borderRadius: 10,
    border: '1px solid rgba(134,239,172,0.24)',
    background: 'rgba(74,222,128,0.08)',
    color: '#b7f3c9',
    fontSize: 12,
    fontWeight: 700,
    cursor: 'pointer',
  },
  eyebrow: {
    fontFamily: 'var(--v2-mono)',
    fontSize: 11,
    color: 'var(--v2-ink-3)',
    letterSpacing: '0.16em',
    textTransform: 'uppercase',
    marginBottom: 10,
  },
  subhead: {
    marginTop: 8,
    fontSize: 15,
    lineHeight: 1.7,
    color: 'var(--v2-ink-2)',
    maxWidth: 760,
  },
  card: {
    background: 'var(--v2-bg-2)',
    border: '1px solid var(--v2-line)',
    borderRadius: 16,
    padding: 20,
  },
  cardLabel: {
    fontFamily: 'var(--v2-mono)',
    fontSize: 10,
    color: 'var(--v2-ink-3)',
    letterSpacing: '0.16em',
    textTransform: 'uppercase',
    marginBottom: 12,
  },
  statValue: {
    fontSize: 24,
    fontWeight: 700,
    letterSpacing: '-0.03em',
    color: 'var(--v2-ink)',
    marginBottom: 8,
  },
  statSub: {
    fontSize: 13,
    color: 'var(--v2-ink-3)',
  },
  estimateTitle: {
    fontSize: 15,
    fontWeight: 700,
    color: 'var(--v2-ink)',
    marginBottom: 4,
  },
  estimateMeta: {
    fontFamily: 'var(--v2-mono)',
    fontSize: 12,
    color: 'var(--v2-ink-3)',
    lineHeight: 1.6,
  },
  emptyState: {
    padding: '14px 0',
    color: 'var(--v2-ink-3)',
    fontSize: 14,
  },
  mutedText: {
    color: 'var(--v2-ink-3)',
    fontSize: 14,
  },
  bodyText: {
    fontSize: 14,
    lineHeight: 1.6,
    color: 'var(--v2-ink-3)',
  },
  bodyTextStrong: {
    fontSize: 14,
    lineHeight: 1.7,
    color: 'var(--v2-ink-2)',
  },
  grid10: {
    display: 'grid',
    gap: 10,
  },
  grid12: {
    display: 'grid',
    gap: 12,
  },
  grid14: {
    display: 'grid',
    gap: 14,
  },
  grid16: {
    display: 'grid',
    gap: 16,
  },
  grid18: {
    display: 'grid',
    gap: 18,
  },
  rowWrap: {
    display: 'flex',
    gap: 10,
    flexWrap: 'wrap',
  },
  rowWrapEnd: {
    display: 'flex',
    gap: 8,
    flexWrap: 'wrap',
    justifyContent: 'flex-end',
  },
  inlineMetaRow: {
    display: 'flex',
    alignItems: 'baseline',
    gap: 10,
    flexWrap: 'wrap',
  },
  sectionStack: {
    display: 'grid',
    gap: 14,
    alignSelf: 'start',
  },
  sectionStackLg: {
    display: 'grid',
    gap: 22,
    alignSelf: 'start',
  },
  feedbackWrap: {
    marginBottom: 18,
  },
  feedbackDetails: {
    display: 'grid',
    gap: 6,
  },
  mobileLinkCard: {
    display: 'block',
    borderRadius: 14,
    border: '1px solid var(--v2-line)',
    background: 'var(--v2-bg-2)',
    padding: 14,
    color: 'var(--v2-ink)',
    textDecoration: 'none',
  },
  jobListScroll: {
    display: 'grid',
    gap: 10,
    maxHeight: 620,
    overflowY: 'auto',
    paddingRight: 4,
  },
  emptyPanel: {
    borderRadius: 14,
    border: '1px solid var(--v2-line)',
    background: 'var(--v2-bg-2)',
    padding: 16,
    display: 'grid',
    gap: 12,
  },
  emptyPanelTitle: {
    fontSize: 15,
    fontWeight: 700,
    color: 'var(--v2-ink)',
  },
  selectableItem: {
    textAlign: 'left',
    borderRadius: 14,
    border: '1px solid var(--v2-line)',
    background: 'var(--v2-bg-2)',
    padding: 14,
    color: 'var(--v2-ink)',
    cursor: 'pointer',
  },
  selectableItemSelected: {
    textAlign: 'left',
    borderRadius: 14,
    border: '1px solid var(--v2-green)',
    background: 'var(--v2-green-wash)',
    padding: 14,
    color: 'var(--v2-ink)',
    cursor: 'pointer',
  },
  itemTitle: {
    fontSize: 14,
    fontWeight: 700,
    color: 'var(--v2-ink)',
  },
  itemTitleSpaced: {
    fontSize: 14,
    fontWeight: 700,
    color: 'var(--v2-ink)',
    marginBottom: 3,
  },
  itemSubtleTitle: {
    fontSize: 14,
    marginBottom: 3,
    color: 'var(--v2-ink)',
  },
  itemMeta: {
    fontSize: 14,
    color: 'var(--v2-ink-3)',
  },
  itemMetaMono: {
    fontFamily: 'var(--v2-mono)',
    fontSize: 11,
    color: 'var(--v2-ink-3)',
    marginTop: 4,
  },
  versionRow: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr) auto',
    gap: 14,
    alignItems: 'center',
    borderTop: '1px solid var(--v2-line)',
    paddingTop: 14,
  },
  versionTotal: {
    fontSize: 14,
    fontWeight: 700,
    color: 'var(--v2-green-2)',
  },
  createFields: {
    display: 'grid',
    gap: 16,
  },
  selectedJobTitle: {
    fontSize: 26,
    lineHeight: 1.1,
    letterSpacing: '-0.03em',
    fontWeight: 700,
    color: 'var(--v2-ink)',
  },
  selectedJobStatsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
    gap: 12,
  },
  selectedJobStatCard: {
    borderRadius: 14,
    border: '1px solid var(--v2-line)',
    background: 'var(--v2-bg-2)',
    padding: 14,
  },
  selectedJobStatLabel: {
    fontFamily: 'var(--v2-mono)',
    fontSize: 10,
    color: 'var(--v2-ink-3)',
    letterSpacing: '0.16em',
    textTransform: 'uppercase',
    marginBottom: 8,
  },
  selectedJobStatValue: {
    fontSize: 15,
    fontWeight: 700,
    color: 'var(--v2-ink)',
  },
  mobileSectionLabel: {
    fontFamily: 'var(--v2-mono)',
    fontSize: 10,
    color: 'var(--v2-ink-3)',
    letterSpacing: '0.16em',
    textTransform: 'uppercase',
    marginBottom: 8,
  },
}
