import assert from 'node:assert/strict'
import test from 'node:test'
import { recalculateEditorDraftFactors } from '../../../app/crm/quotes/[id]/_lib/estimateV2EditorRecalculate.ts'

test('recalculateEditorDraftFactors syncs wall, ceiling, and trim factors and strips invalid trim helper mode', () => {
  const result = recalculateEditorDraftFactors({
    rooms: [
      {
        id: 'room-1',
        roomId: 'R001',
        roomName: 'Living',
        roomTypeId: '',
        lengthIn: '144',
        widthIn: '120',
        heightIn: '120',
        wallComplexityId: 'WALL_STD',
        notes: '',
        position: 0,
      },
    ],
    wallScopes: [
      {
        id: 'wall-1',
        roomId: 'R001',
        position: 0,
        mode: 'SEG',
        include: 'Y',
        scopeName: '',
        colorId: 'COLOR1',
        paintProductId: '',
        primerProductId: '',
        primeMode: 'NONE',
        heightIn: '',
        perimeterIn: '',
        standardDoorCount: '',
        standardWindowCount: '',
        heightFactor: '0.5',
        complexityFactor: '0.5',
        wallFlagFactor: '0.5',
        cutInTopFactor: '1',
        cutInBottomFactor: '1',
        paintCoats: '2',
        primerCoats: '1',
        spotPrimePercent: '',
        overrideAreaSqFt: '',
        overridePaintHours: '',
        overridePrimerHours: '',
        overridePaintGallons: '',
        overridePrimerGallons: '',
        overrideSupplyCost: '',
        overrideTotal: '',
        notes: '',
      },
    ],
    ceilingScopes: [
      {
        id: 'ceiling-1',
        roomId: 'R001',
        position: 0,
        mode: 'SEG',
        include: 'Y',
        scopeName: '',
        colorId: 'COLOR1',
        paintProductId: '',
        primerProductId: '',
        primeMode: 'NONE',
        spotPrimePercent: '',
        ceilingTypeId: '',
        lengthIn: '',
        widthIn: '',
        areaSf: '',
        heightFactor: '0.5',
        complexityFactor: '0.5',
        ceilingFlagFactor: '0.5',
        paintCoats: '1',
        primerCoats: '1',
        overrideAreaSqFt: '',
        overridePaintHours: '',
        overridePrimerHours: '',
        overridePaintGallons: '',
        overridePrimerGallons: '',
        overrideSupplyCost: '',
        overrideTotal: '',
        notes: '',
      },
    ],
    trimScopes: [
      {
        id: 'trim-1',
        roomId: 'R001',
        position: 0,
        include: 'Y',
        scopeName: 'Baseboard',
        trimTypeId: 'TRIM_BASE',
        trimFamily: '',
        unitType: 'LF',
        measurementMode: 'ROOM_HELPER',
        helperSource: 'ROOM_PERIMETER',
        measurementValue: '',
        helperValue: '',
        colorId: '',
        paintProductId: '',
        primerProductId: '',
        paintEnabled: 'Y',
        primeMode: 'NONE',
        spotPrimePercent: '',
        productionRateId: '',
        prepFactor: '1',
        heightFactor: '0.5',
        profileFactor: '1',
        roomFlagFactor: '0.5',
        maskingFactor: '1',
        stairFactor: '1',
        difficultFinishFactor: '1',
        caulkFillFactor: '1',
        paintCoats: '2',
        primerCoats: '1',
        overrideMeasurement: '',
        overrideHours: '',
        overrideGallons: '',
        overrideSupplyCost: '',
        overrideTotal: '',
        overrideDescription: '',
        notes: '',
      },
    ],
    roomFlags: [
      {
        id: 'flag-1',
        roomId: 'R001',
        flagId: 'FLAG_HIGH',
        position: 0,
      },
    ],
    catalogs: {
      paint_products: [],
      color_codes: [],
      production_rates: [
        {
          id: 'WALL_STD',
          label: 'Standard',
          scope_id: 'WALLS',
          sqft_per_hr: 100,
          prep_sqft_per_hr: null,
          primer_sqft_per_hr: null,
          surface_type: null,
          condition: null,
        },
      ],
      height_factors: [
        { id: 'HEIGHT_TALL', label: 'Tall', min_height_ft: 9, max_height_ft: null, labor_multiplier: 1.2 },
      ],
      room_types: [],
      room_flags: [
        { id: 'FLAG_HIGH', label: 'Difficult', wall_factor: 1.15, ceil_factor: 1.1, trim_factor: 1.05 },
      ],
      ceiling_types: [],
      trim_items: [],
    },
    trimTypeOptions: [
      {
        id: 'TRIM_BASE',
        label: 'Baseboard',
        family: 'BASE',
        category: 'Base',
        unit_type: 'LF',
        helper_allowed: true,
        default_production_rate_id: null,
      },
    ],
  })

  assert.equal(result.wallScopes[0].heightFactor, '1.2')
  assert.equal(result.wallScopes[0].complexityFactor, '1.5')
  assert.equal(result.wallScopes[0].wallFlagFactor, '1.15')
  assert.equal(result.ceilingScopes[0].ceilingFlagFactor, '1.1')
  assert.equal(result.trimScopes[0].roomFlagFactor, '1.05')
  assert.equal(result.trimScopes[0].measurementMode, 'MANUAL')
  assert.equal(result.roomModeById.get('R001'), 'SEG')
})
