import assert from 'node:assert/strict'
import test from 'node:test'
import { calculateWalls, type WallCalculationInput } from '../walls.ts'

function approx(actual: number | null | undefined, expected: number, epsilon = 0.0001) {
  assert.notEqual(actual, null)
  assert.notEqual(actual, undefined)
  assert.ok(Math.abs((actual as number) - expected) <= epsilon, `expected ${expected}, got ${actual}`)
}

test('prime mode matrix covers NONE, SPOT, FULL and clamps spot percent over 100', () => {
  const input: WallCalculationInput = {
    settings: {
      labor_rate_per_hour: 1,
      paint_prod_rate_sqft_per_hour: 100,
      primer_prod_rate_sqft_per_hour: 100,
      paint_coverage_sqft_per_gal_per_coat: 100,
      primer_coverage_sqft_per_gal_per_coat: 100,
      paint_coats: 1,
      primer_coats: 1,
      area_supply_cost_per_sf: 0,
      per_color_supply_cost: 0,
      paint_price_per_gal: 0,
      primer_price_per_gal: 0,
      spot_prime_percent: 30,
    },
    scopes: [
      {
        id: 'scope-none',
        room_id: 'R001',
        position: 0,
        mode: 'RECT',
        include: 'Y',
        scope_name: null,
        color_id: null,
        paint_product_id: null,
        primer_product_id: null,
        prime_mode: 'NONE',
        height_in: 96,
        perimeter_in: 150,
        standard_door_count: 0,
        standard_window_count: 0,
        height_factor: 1,
        complexity_factor: 1,
        wall_flag_factor: 1,
        cut_in_top_factor: 1,
        cut_in_bottom_factor: 1,
        raw_area_sf: null,
        override_area_sf: null,
        effective_area_sf: null,
        raw_paint_hours: null,
        override_paint_hours: null,
        effective_paint_hours: null,
        raw_primer_hours: null,
        override_primer_hours: null,
        effective_primer_hours: null,
        raw_paint_gallons: null,
        override_paint_gallons: null,
        effective_paint_gallons: null,
        raw_primer_gallons: null,
        override_primer_gallons: null,
        effective_primer_gallons: null,
        raw_supply_cost: null,
        override_supply_cost: null,
        effective_supply_cost: null,
        raw_total: null,
        override_total: null,
        effective_total: null,
        notes: null,
      },
      {
        id: 'scope-spot',
        room_id: 'R001',
        position: 1,
        mode: 'RECT',
        include: 'Y',
        scope_name: null,
        color_id: null,
        paint_product_id: null,
        primer_product_id: null,
        prime_mode: 'SPOT',
        height_in: 96,
        perimeter_in: 150,
        standard_door_count: 0,
        standard_window_count: 0,
        height_factor: 1,
        complexity_factor: 1,
        wall_flag_factor: 1,
        cut_in_top_factor: 1,
        cut_in_bottom_factor: 1,
        raw_area_sf: null,
        override_area_sf: null,
        effective_area_sf: null,
        raw_paint_hours: null,
        override_paint_hours: null,
        effective_paint_hours: null,
        raw_primer_hours: null,
        override_primer_hours: null,
        effective_primer_hours: null,
        raw_paint_gallons: null,
        override_paint_gallons: null,
        effective_paint_gallons: null,
        raw_primer_gallons: null,
        override_primer_gallons: null,
        effective_primer_gallons: null,
        raw_supply_cost: null,
        override_supply_cost: null,
        effective_supply_cost: null,
        raw_total: null,
        override_total: null,
        effective_total: null,
        notes: null,
        spot_prime_percent: 25,
      },
      {
        id: 'scope-full',
        room_id: 'R001',
        position: 2,
        mode: 'RECT',
        include: 'Y',
        scope_name: null,
        color_id: null,
        paint_product_id: null,
        primer_product_id: null,
        prime_mode: 'FULL',
        height_in: 96,
        perimeter_in: 150,
        standard_door_count: 0,
        standard_window_count: 0,
        height_factor: 1,
        complexity_factor: 1,
        wall_flag_factor: 1,
        cut_in_top_factor: 1,
        cut_in_bottom_factor: 1,
        raw_area_sf: null,
        override_area_sf: null,
        effective_area_sf: null,
        raw_paint_hours: null,
        override_paint_hours: null,
        effective_paint_hours: null,
        raw_primer_hours: null,
        override_primer_hours: null,
        effective_primer_hours: null,
        raw_paint_gallons: null,
        override_paint_gallons: null,
        effective_paint_gallons: null,
        raw_primer_gallons: null,
        override_primer_gallons: null,
        effective_primer_gallons: null,
        raw_supply_cost: null,
        override_supply_cost: null,
        effective_supply_cost: null,
        raw_total: null,
        override_total: null,
        effective_total: null,
        notes: null,
      },
      {
        id: 'scope-spot-clamped',
        room_id: 'R001',
        position: 3,
        mode: 'RECT',
        include: 'Y',
        scope_name: null,
        color_id: null,
        paint_product_id: null,
        primer_product_id: null,
        prime_mode: 'SPOT',
        height_in: 96,
        perimeter_in: 150,
        standard_door_count: 0,
        standard_window_count: 0,
        height_factor: 1,
        complexity_factor: 1,
        wall_flag_factor: 1,
        cut_in_top_factor: 1,
        cut_in_bottom_factor: 1,
        raw_area_sf: null,
        override_area_sf: null,
        effective_area_sf: null,
        raw_paint_hours: null,
        override_paint_hours: null,
        effective_paint_hours: null,
        raw_primer_hours: null,
        override_primer_hours: null,
        effective_primer_hours: null,
        raw_paint_gallons: null,
        override_paint_gallons: null,
        effective_paint_gallons: null,
        raw_primer_gallons: null,
        override_primer_gallons: null,
        effective_primer_gallons: null,
        raw_supply_cost: null,
        override_supply_cost: null,
        effective_supply_cost: null,
        raw_total: null,
        override_total: null,
        effective_total: null,
        notes: null,
        spot_prime_percent: 250,
      },
    ],
    segments: [],
  }

  const result = calculateWalls(input)
  const none = result.scopes.find((scope) => scope.id === 'scope-none')
  const spot = result.scopes.find((scope) => scope.id === 'scope-spot')
  const full = result.scopes.find((scope) => scope.id === 'scope-full')
  const spotClamped = result.scopes.find((scope) => scope.id === 'scope-spot-clamped')
  assert.ok(none && spot && full && spotClamped)
  approx(none.raw_primer_hours, 0)
  approx(spot.raw_primer_hours, 0.25)
  approx(full.raw_primer_hours, 1)
  approx(spotClamped.raw_primer_hours, 1)
  approx(none.raw_primer_gallons, 0)
  approx(spot.raw_primer_gallons, 0.25)
  approx(full.raw_primer_gallons, 1)
  approx(spotClamped.raw_primer_gallons, 1)
})

test('include N produces zero effective computed metrics when no total override is set', () => {
  const input: WallCalculationInput = {
    settings: {
      labor_rate_per_hour: 70,
      paint_prod_rate_sqft_per_hour: 120,
      primer_prod_rate_sqft_per_hour: 160,
      paint_coverage_sqft_per_gal_per_coat: 350,
      primer_coverage_sqft_per_gal_per_coat: 300,
      paint_coats: 2,
      primer_coats: 1,
      area_supply_cost_per_sf: 0.2,
      per_color_supply_cost: 25,
      paint_price_per_gal: 50,
      primer_price_per_gal: 40,
    },
    scopes: [
      {
        id: 'scope-excluded',
        room_id: 'R099',
        position: 0,
        mode: 'RECT',
        include: 'N',
        scope_name: null,
        color_id: 'A',
        paint_product_id: 'W',
        primer_product_id: 'P',
        prime_mode: 'FULL',
        height_in: 96,
        perimeter_in: 500,
        standard_door_count: 0,
        standard_window_count: 0,
        height_factor: 1,
        complexity_factor: 1,
        wall_flag_factor: 1,
        cut_in_top_factor: 1,
        cut_in_bottom_factor: 1,
        raw_area_sf: null,
        override_area_sf: null,
        effective_area_sf: null,
        raw_paint_hours: null,
        override_paint_hours: null,
        effective_paint_hours: null,
        raw_primer_hours: null,
        override_primer_hours: null,
        effective_primer_hours: null,
        raw_paint_gallons: null,
        override_paint_gallons: null,
        effective_paint_gallons: null,
        raw_primer_gallons: null,
        override_primer_gallons: null,
        effective_primer_gallons: null,
        raw_supply_cost: null,
        override_supply_cost: null,
        effective_supply_cost: null,
        raw_total: null,
        override_total: null,
        effective_total: null,
        notes: null,
      },
    ],
    segments: [],
  }

  const result = calculateWalls(input)
  const scope = result.scopes[0]
  approx(scope.effective_area_sf, 0)
  approx(scope.effective_paint_hours, 0)
  approx(scope.effective_primer_hours, 0)
  approx(scope.effective_paint_gallons, 0)
  approx(scope.effective_primer_gallons, 0)
  approx(scope.effective_supply_cost, 0)
  approx(scope.effective_total, 0)
})

test('override_total and override_supply_cost take precedence when provided', () => {
  const input: WallCalculationInput = {
    scopes: [
      {
        id: 'scope-override',
        room_id: 'R020',
        position: 0,
        mode: 'RECT',
        include: 'Y',
        scope_name: null,
        color_id: null,
        paint_product_id: null,
        primer_product_id: null,
        prime_mode: 'NONE',
        height_in: 96,
        perimeter_in: 300,
        standard_door_count: 0,
        standard_window_count: 0,
        height_factor: 1,
        complexity_factor: 1,
        wall_flag_factor: 1,
        cut_in_top_factor: 1,
        cut_in_bottom_factor: 1,
        raw_area_sf: null,
        override_area_sf: null,
        effective_area_sf: null,
        raw_paint_hours: null,
        override_paint_hours: null,
        effective_paint_hours: null,
        raw_primer_hours: null,
        override_primer_hours: null,
        effective_primer_hours: null,
        raw_paint_gallons: null,
        override_paint_gallons: null,
        effective_paint_gallons: null,
        raw_primer_gallons: null,
        override_primer_gallons: null,
        effective_primer_gallons: null,
        raw_supply_cost: null,
        override_supply_cost: 33,
        effective_supply_cost: null,
        raw_total: null,
        override_total: 777,
        effective_total: null,
        notes: null,
      },
    ],
    segments: [],
  }
  const result = calculateWalls(input)
  assert.equal(result.scopes.length, 1)
  approx(result.scopes[0].effective_supply_cost, 33)
  approx(result.scopes[0].effective_total, 777)
  approx(result.scope_traces[0].supplies.effective_supply_cost, 33)
  approx(result.scope_traces[0].totals.effective_total, 777)
})

test('segment shape edge-case matrix reports missing required fields and SEG missing-included-segment', () => {
  const input: WallCalculationInput = {
    scopes: [
      {
        id: 'scope-rect-missing',
        room_id: 'R301',
        position: 0,
        mode: 'SEG',
        include: 'Y',
        scope_name: null,
        color_id: null,
        paint_product_id: null,
        primer_product_id: null,
        prime_mode: 'NONE',
        height_in: null,
        perimeter_in: null,
        standard_door_count: null,
        standard_window_count: null,
        height_factor: 1,
        complexity_factor: 1,
        wall_flag_factor: 1,
        cut_in_top_factor: 1,
        cut_in_bottom_factor: 1,
        raw_area_sf: null,
        override_area_sf: null,
        effective_area_sf: null,
        raw_paint_hours: null,
        override_paint_hours: null,
        effective_paint_hours: null,
        raw_primer_hours: null,
        override_primer_hours: null,
        effective_primer_hours: null,
        raw_paint_gallons: null,
        override_paint_gallons: null,
        effective_paint_gallons: null,
        raw_primer_gallons: null,
        override_primer_gallons: null,
        effective_primer_gallons: null,
        raw_supply_cost: null,
        override_supply_cost: null,
        effective_supply_cost: null,
        raw_total: null,
        override_total: null,
        effective_total: null,
        notes: null,
      },
      {
        id: 'scope-triangle-missing',
        room_id: 'R302',
        position: 0,
        mode: 'SEG',
        include: 'Y',
        scope_name: null,
        color_id: null,
        paint_product_id: null,
        primer_product_id: null,
        prime_mode: 'NONE',
        height_in: null,
        perimeter_in: null,
        standard_door_count: null,
        standard_window_count: null,
        height_factor: 1,
        complexity_factor: 1,
        wall_flag_factor: 1,
        cut_in_top_factor: 1,
        cut_in_bottom_factor: 1,
        raw_area_sf: null,
        override_area_sf: null,
        effective_area_sf: null,
        raw_paint_hours: null,
        override_paint_hours: null,
        effective_paint_hours: null,
        raw_primer_hours: null,
        override_primer_hours: null,
        effective_primer_hours: null,
        raw_paint_gallons: null,
        override_paint_gallons: null,
        effective_paint_gallons: null,
        raw_primer_gallons: null,
        override_primer_gallons: null,
        effective_primer_gallons: null,
        raw_supply_cost: null,
        override_supply_cost: null,
        effective_supply_cost: null,
        raw_total: null,
        override_total: null,
        effective_total: null,
        notes: null,
      },
      {
        id: 'scope-manual-missing',
        room_id: 'R303',
        position: 0,
        mode: 'SEG',
        include: 'Y',
        scope_name: null,
        color_id: null,
        paint_product_id: null,
        primer_product_id: null,
        prime_mode: 'NONE',
        height_in: null,
        perimeter_in: null,
        standard_door_count: null,
        standard_window_count: null,
        height_factor: 1,
        complexity_factor: 1,
        wall_flag_factor: 1,
        cut_in_top_factor: 1,
        cut_in_bottom_factor: 1,
        raw_area_sf: null,
        override_area_sf: null,
        effective_area_sf: null,
        raw_paint_hours: null,
        override_paint_hours: null,
        effective_paint_hours: null,
        raw_primer_hours: null,
        override_primer_hours: null,
        effective_primer_hours: null,
        raw_paint_gallons: null,
        override_paint_gallons: null,
        effective_paint_gallons: null,
        raw_primer_gallons: null,
        override_primer_gallons: null,
        effective_primer_gallons: null,
        raw_supply_cost: null,
        override_supply_cost: null,
        effective_supply_cost: null,
        raw_total: null,
        override_total: null,
        effective_total: null,
        notes: null,
      },
      {
        id: 'scope-no-included',
        room_id: 'R304',
        position: 0,
        mode: 'SEG',
        include: 'Y',
        scope_name: null,
        color_id: null,
        paint_product_id: null,
        primer_product_id: null,
        prime_mode: 'NONE',
        height_in: null,
        perimeter_in: null,
        standard_door_count: null,
        standard_window_count: null,
        height_factor: 1,
        complexity_factor: 1,
        wall_flag_factor: 1,
        cut_in_top_factor: 1,
        cut_in_bottom_factor: 1,
        raw_area_sf: null,
        override_area_sf: null,
        effective_area_sf: null,
        raw_paint_hours: null,
        override_paint_hours: null,
        effective_paint_hours: null,
        raw_primer_hours: null,
        override_primer_hours: null,
        effective_primer_hours: null,
        raw_paint_gallons: null,
        override_paint_gallons: null,
        effective_paint_gallons: null,
        raw_primer_gallons: null,
        override_primer_gallons: null,
        effective_primer_gallons: null,
        raw_supply_cost: null,
        override_supply_cost: null,
        effective_supply_cost: null,
        raw_total: null,
        override_total: null,
        effective_total: null,
        notes: null,
      },
    ],
    segments: [
      {
        id: 'seg-rect-missing',
        wall_scope_id: 'scope-rect-missing',
        room_id: 'R301',
        position: 0,
        segment_name: null,
        include: 'Y',
        shape_type: 'RECTANGLE',
        quantity: 1,
        width_in: null,
        height_in: 96,
        base_in: null,
        manual_area_sf: null,
        standard_door_count: 0,
        standard_window_count: 0,
        raw_area_sf: null,
        override_area_sf: null,
        effective_area_sf: null,
        notes: null,
      },
      {
        id: 'seg-triangle-missing',
        wall_scope_id: 'scope-triangle-missing',
        room_id: 'R302',
        position: 0,
        segment_name: null,
        include: 'Y',
        shape_type: 'TRIANGLE',
        quantity: 1,
        width_in: null,
        height_in: 96,
        base_in: null,
        manual_area_sf: null,
        standard_door_count: 0,
        standard_window_count: 0,
        raw_area_sf: null,
        override_area_sf: null,
        effective_area_sf: null,
        notes: null,
      },
      {
        id: 'seg-manual-missing',
        wall_scope_id: 'scope-manual-missing',
        room_id: 'R303',
        position: 0,
        segment_name: null,
        include: 'Y',
        shape_type: 'MANUAL',
        quantity: 1,
        width_in: null,
        height_in: null,
        base_in: null,
        manual_area_sf: null,
        standard_door_count: 0,
        standard_window_count: 0,
        raw_area_sf: null,
        override_area_sf: null,
        effective_area_sf: null,
        notes: null,
      },
      {
        id: 'seg-excluded',
        wall_scope_id: 'scope-no-included',
        room_id: 'R304',
        position: 0,
        segment_name: null,
        include: 'N',
        shape_type: 'MANUAL',
        quantity: 1,
        width_in: null,
        height_in: null,
        base_in: null,
        manual_area_sf: 40,
        standard_door_count: 0,
        standard_window_count: 0,
        raw_area_sf: null,
        override_area_sf: null,
        effective_area_sf: null,
        notes: null,
      },
    ],
  }

  const result = calculateWalls(input)
  const missingFields = result.missing_inputs.map((item) => item.field)
  assert.ok(missingFields.includes('width_in'))
  assert.ok(missingFields.includes('base_in'))
  assert.ok(missingFields.includes('manual_area_sf'))
  assert.ok(missingFields.includes('wall_segments'))
})

test('per-color group uses max per_color_supply_cost override in group', () => {
  const input: WallCalculationInput = {
    settings: {
      area_supply_cost_per_sf: 0,
      per_color_supply_cost: 20,
      paint_prod_rate_sqft_per_hour: 1000,
      primer_prod_rate_sqft_per_hour: 1000,
      paint_coverage_sqft_per_gal_per_coat: 500,
      primer_coverage_sqft_per_gal_per_coat: 500,
      labor_rate_per_hour: 1,
      paint_coats: 1,
      primer_coats: 1,
    },
    scopes: [
      {
        id: 'scope-a',
        room_id: 'R400',
        position: 0,
        mode: 'RECT',
        include: 'Y',
        scope_name: null,
        color_id: 'Z',
        paint_product_id: 'W',
        primer_product_id: null,
        prime_mode: 'NONE',
        height_in: 96,
        perimeter_in: 150,
        standard_door_count: 0,
        standard_window_count: 0,
        height_factor: 1,
        complexity_factor: 1,
        wall_flag_factor: 1,
        cut_in_top_factor: 1,
        cut_in_bottom_factor: 1,
        raw_area_sf: null,
        override_area_sf: null,
        effective_area_sf: null,
        raw_paint_hours: null,
        override_paint_hours: null,
        effective_paint_hours: null,
        raw_primer_hours: null,
        override_primer_hours: null,
        effective_primer_hours: null,
        raw_paint_gallons: null,
        override_paint_gallons: null,
        effective_paint_gallons: null,
        raw_primer_gallons: null,
        override_primer_gallons: null,
        effective_primer_gallons: null,
        raw_supply_cost: null,
        override_supply_cost: null,
        effective_supply_cost: null,
        raw_total: null,
        override_total: null,
        effective_total: null,
        notes: null,
        per_color_supply_cost: 12,
      },
      {
        id: 'scope-b',
        room_id: 'R401',
        position: 0,
        mode: 'RECT',
        include: 'Y',
        scope_name: null,
        color_id: 'Z',
        paint_product_id: 'W',
        primer_product_id: null,
        prime_mode: 'NONE',
        height_in: 96,
        perimeter_in: 150,
        standard_door_count: 0,
        standard_window_count: 0,
        height_factor: 1,
        complexity_factor: 1,
        wall_flag_factor: 1,
        cut_in_top_factor: 1,
        cut_in_bottom_factor: 1,
        raw_area_sf: null,
        override_area_sf: null,
        effective_area_sf: null,
        raw_paint_hours: null,
        override_paint_hours: null,
        effective_paint_hours: null,
        raw_primer_hours: null,
        override_primer_hours: null,
        effective_primer_hours: null,
        raw_paint_gallons: null,
        override_paint_gallons: null,
        effective_paint_gallons: null,
        raw_primer_gallons: null,
        override_primer_gallons: null,
        effective_primer_gallons: null,
        raw_supply_cost: null,
        override_supply_cost: null,
        effective_supply_cost: null,
        raw_total: null,
        override_total: null,
        effective_total: null,
        notes: null,
        per_color_supply_cost: 30,
      },
    ],
    segments: [],
  }

  const result = calculateWalls(input)
  assert.equal(result.per_color_supply_groups.length, 1)
  const group = result.per_color_supply_groups[0]
  approx(group.total_shared_supply_cost, 30)
  assert.equal(group.allocations.length, 2)
  approx(group.allocations[0].allocated_supply_cost, 15)
  approx(group.allocations[1].allocated_supply_cost, 15)
})
