'use client'

import type { EstimateV2EditorStoreApi } from '@/lib/estimates/v2/store/estimateV2Store'
import { useEstimateV2EditorDerivedSections } from './useEstimateV2EditorDerivedSections'

export function useEstimateV2DerivedState(params: { store: EstimateV2EditorStoreApi }) {
  const sections = useEstimateV2EditorDerivedSections(params)

  return {
    sections,
    wallProductionRates: sections.catalog.wallProductionRates,
    trimProductionRates: sections.catalog.trimProductionRates,
    wallProductionRateById: sections.catalog.wallProductionRateById,
    trimTypeOptions: sections.catalog.trimTypeOptions,
    roomFlagById: sections.catalog.roomFlagById,
    roomModeById: sections.room.roomModeById,
    selectedRoom: sections.room.selectedRoom,
    roomScopeByRoomId: sections.room.roomScopeByRoomId,
    roomCeilingScopeByRoomId: sections.room.roomCeilingScopeByRoomId,
    roomTrimScopeByRoomId: sections.room.roomTrimScopeByRoomId,
    selectedRoomScopes: sections.room.selectedRoomScopes,
    selectedRoomCeilingScopes: sections.room.selectedRoomCeilingScopes,
    selectedRoomTrimScopes: sections.room.selectedRoomTrimScopes,
    firstScope: sections.room.firstScope,
    firstCeilingScope: sections.room.firstCeilingScope,
    firstTrimScope: sections.room.firstTrimScope,
    wallsIncluded: sections.room.wallsIncluded,
    ceilingsIncluded: sections.room.ceilingsIncluded,
    trimsIncluded: sections.room.trimsIncluded,
    jobTrimsIncluded: sections.room.jobTrimsIncluded,
    selectedRoomResolvedMode: sections.room.selectedRoomResolvedMode,
    selectedRoomGeometryMode: sections.room.selectedRoomGeometryMode,
    roomComplexityFactorByRoomId: sections.room.roomComplexityFactorByRoomId,
    roomWallFlagFactorByRoomId: sections.room.roomWallFlagFactorByRoomId,
    roomCeilingFlagFactorByRoomId: sections.room.roomCeilingFlagFactorByRoomId,
    roomTrimFlagFactorByRoomId: sections.room.roomTrimFlagFactorByRoomId,
    roomHeightFactorByRoomId: sections.room.roomHeightFactorByRoomId,
    displayedSegmentEffectiveAreaById: sections.calculation.displayedSegmentEffectiveAreaById,
    displayedScopeEffectiveAreaById: sections.calculation.displayedScopeEffectiveAreaById,
    displayedRoomEffectiveAreaByRoomId: sections.calculation.displayedRoomEffectiveAreaByRoomId,
    wallScopeEffectiveTotalById: sections.calculation.wallScopeEffectiveTotalById,
    selectedCeilingEffectiveSqFt: sections.calculation.selectedCeilingEffectiveSqFt,
    ceilingScopeEffectiveTotalById: sections.calculation.ceilingScopeEffectiveTotalById,
    trimScopeEffectiveMeasurementById: sections.calculation.trimScopeEffectiveMeasurementById,
    trimScopeEffectiveTotalById: sections.calculation.trimScopeEffectiveTotalById,
    selectedWallSubtotal: sections.calculation.selectedWallSubtotal,
    selectedCeilingSubtotal: sections.calculation.selectedCeilingSubtotal,
    totalEffectiveAreaSqFt: sections.calculation.totalEffectiveAreaSqFt,
    activeScopeTotals: sections.calculation.activeScopeTotals,
    selectedRoomEffectiveSqFt: sections.calculation.selectedRoomEffectiveSqFt,
    selectedScopeEffectiveSqFt: sections.calculation.selectedScopeEffectiveSqFt,
    activeRoomFlagCount: sections.room.activeRoomFlagCount,
    selectedRoomIssueCount: sections.room.selectedRoomIssueCount,
    colorCodeOptions: sections.catalog.colorCodeOptions,
    defaultColorCodeId: sections.catalog.defaultColorCodeId,
    productLabelById: sections.catalog.productLabelById,
    allPaintProducts: sections.catalog.allPaintProducts,
    allPrimerProducts: sections.catalog.allPrimerProducts,
    paintOptions: sections.catalog.paintOptions,
    wallPaintOptions: sections.catalog.wallPaintOptions,
    ceilingPaintOptions: sections.catalog.ceilingPaintOptions,
    trimPaintOptions: sections.catalog.trimPaintOptions,
    wallPrimerOptions: sections.catalog.wallPrimerOptions,
    ceilingPrimerOptions: sections.catalog.ceilingPrimerOptions,
    trimPrimerOptions: sections.catalog.trimPrimerOptions,
    roomTypeOptions: sections.catalog.roomTypeOptions,
    calculationsStale: sections.calculation.calculationsStale,
    wallPaintLabel: sections.productLabels.wallPaintLabel,
    wallPrimerLabel: sections.productLabels.wallPrimerLabel,
    ceilingPaintLabel: sections.productLabels.ceilingPaintLabel,
    ceilingPrimerLabel: sections.productLabels.ceilingPrimerLabel,
    trimPaintLabel: sections.productLabels.trimPaintLabel,
    trimPrimerLabel: sections.productLabels.trimPrimerLabel,
    selectedTrimSubtotal: sections.calculation.selectedTrimSubtotal,
    selectedTrimMeasurement: sections.calculation.selectedTrimMeasurement,
    saveStatusText: sections.save.saveStatusText,
    saveStatusColor: sections.save.saveStatusColor,
    orgWallPaintLabel: sections.productLabels.orgWallPaintLabel,
    orgWallPrimerLabel: sections.productLabels.orgWallPrimerLabel,
    orgCeilingPaintLabel: sections.productLabels.orgCeilingPaintLabel,
    orgCeilingPrimerLabel: sections.productLabels.orgCeilingPrimerLabel,
    orgTrimPaintLabel: sections.productLabels.orgTrimPaintLabel,
    orgTrimPrimerLabel: sections.productLabels.orgTrimPrimerLabel,
    effectiveWallPaintLabel: sections.productLabels.effectiveWallPaintLabel,
    effectiveWallPrimerLabel: sections.productLabels.effectiveWallPrimerLabel,
    effectiveCeilingPaintLabel: sections.productLabels.effectiveCeilingPaintLabel,
    effectiveCeilingPrimerLabel: sections.productLabels.effectiveCeilingPrimerLabel,
    effectiveTrimPaintLabel: sections.productLabels.effectiveTrimPaintLabel,
    effectiveTrimPrimerLabel: sections.productLabels.effectiveTrimPrimerLabel,
    dirty: sections.calculation.dirty,
    currentSnapshot: sections.calculation.currentSnapshot,
    currentPayload: sections.calculation.currentPayload,
    useLocalPreviewCalculations: sections.calculation.useLocalPreviewCalculations,
  }
}
